server:
  port: 9700

spring:
  application:
    name: consumer-order
  cloud:
    loadbalancer:
      retry:
        enabled: false


eureka:
  client:
    #false标识不向注册中心注册自己
    registerWithEureka: false
    #false表示注册中心就是自己，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://osc2:9901/eureka/,http://osc:9900/eureka/



feign:
  client:
    config:
      # default 全局配置，超时时间，防止feign重复执行
      default:
        connectTimeout: 2000
        readTimeout: 5000
  hystrix:
    enabled: true

hystrix:
  command:
    #通过feign调用时，可以通过default更新hystrix属性
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    #@hystrixCommad 通过 commandKey 指定
    paymentTimeOut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    feignTimeOut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000