server:
  port: 9811

spring:
  application:
    name: payment-server
  profiles:
    active: 11

eureka:
  client:
    #false标识不向注册中心注册自己
    registerWithEureka: true
    #false表示注册中心就是自己，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://osc2:9901/eureka/,http://osc:9900/eureka/
  instance:
    hostname: osc
    prefer-ip-address: true
    instance-id: payment-server11